#pragma once

#ifndef FLX_SCANCODES_H
#define FLX_SCANCODES_H

enum class FLX_Scancode
{
    FLX_SCANCODE_UNKNOWN = 0,
    FLX_SCANCODE_A = 4,
    FLX_SCANCODE_B = 5,
    FLX_SCANCODE_C = 6,
    FLX_SCANCODE_D = 7,
    FLX_SCANCODE_E = 8,
    FLX_SCANCODE_F = 9,
    FLX_SCANCODE_G = 10,
    FLX_SCANCODE_H = 11,
    FLX_SCANCODE_I = 12,
    FLX_SCANCODE_J = 13,
    FLX_SCANCODE_K = 14,
    FLX_SCANCODE_L = 15,
    FLX_SCANCODE_M = 16,
    FLX_SCANCODE_N = 17,
    FLX_SCANCODE_O = 18,
    FLX_SCANCODE_P = 19,
    FLX_SCANCODE_Q = 20,
    FLX_SCANCODE_R = 21,
    FLX_SCANCODE_S = 22,
    FLX_SCANCODE_T = 23,
    FLX_SCANCODE_U = 24,
    FLX_SCANCODE_V = 25,
    FLX_SCANCODE_W = 26,
    FLX_SCANCODE_X = 27,
    FLX_SCANCODE_Y = 28,
    FLX_SCANCODE_Z = 29,
    FLX_SCANCODE_ESCAPE = 41,
    FLX_SCANCODE_TAB = 43,
    FLX_SCANCODE_SPACE = 44,
    FLX_SCANCODE_RIGHT = 79,
    FLX_SCANCODE_LEFT = 80,
    FLX_SCANCODE_DOWN = 81,
    FLX_SCANCODE_UP = 82,
    FLX_NUM_SCANCODES = 34
};

#endif